create extension if not exists "uuid-ossp";
create extension if not exists vector;
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text, avatar_url text, locale text not null default 'es-MX', created_at timestamptz not null default now());
create table if not exists public.notes (id uuid primary key default uuid_generate_v4(), user_id uuid not null references auth.users(id) on delete cascade, title text not null, source_type text not null, source_name text, source_url text, storage_path text, status text not null default 'queued', language text, summary text, duration_seconds integer, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.transcripts (id uuid primary key default uuid_generate_v4(), note_id uuid not null unique references public.notes(id) on delete cascade, content text not null default '', segments jsonb not null default '[]'::jsonb, speakers jsonb not null default '[]'::jsonb, created_at timestamptz not null default now());
create table if not exists public.note_chunks (id uuid primary key default uuid_generate_v4(), note_id uuid not null references public.notes(id) on delete cascade, content text not null, page_number integer, start_seconds numeric, end_seconds numeric, embedding vector(1536), created_at timestamptz not null default now());
create table if not exists public.flashcards (id uuid primary key default uuid_generate_v4(), user_id uuid not null references auth.users(id) on delete cascade, note_id uuid references public.notes(id) on delete set null, front text not null, back text not null, difficulty text not null default 'new', due_at timestamptz not null default now(), interval_days integer not null default 0, ease_factor numeric not null default 2.5, repetitions integer not null default 0, created_at timestamptz not null default now());
create table if not exists public.quizzes (id uuid primary key default uuid_generate_v4(), user_id uuid not null references auth.users(id) on delete cascade, note_id uuid references public.notes(id) on delete set null, title text not null, question_count integer not null default 0, created_at timestamptz not null default now());
create table if not exists public.quiz_questions (id uuid primary key default uuid_generate_v4(), quiz_id uuid not null references public.quizzes(id) on delete cascade, prompt text not null, options jsonb not null default '[]'::jsonb, answer text, explanation text, source_reference text, position integer not null default 0);
create table if not exists public.chat_messages (id uuid primary key default uuid_generate_v4(), user_id uuid not null references auth.users(id) on delete cascade, note_id uuid not null references public.notes(id) on delete cascade, role text not null, content text not null, citations jsonb not null default '[]'::jsonb, created_at timestamptz not null default now());
create table if not exists public.subscriptions (id uuid primary key default uuid_generate_v4(), user_id uuid not null unique references auth.users(id) on delete cascade, plan text not null default 'free', status text not null default 'active', minutes_used integer not null default 0, minutes_limit integer not null default 60, current_period_end timestamptz, provider_customer_id text, created_at timestamptz not null default now());
alter table public.profiles enable row level security;
alter table public.notes enable row level security;
alter table public.transcripts enable row level security;
alter table public.note_chunks enable row level security;
alter table public.flashcards enable row level security;
alter table public.quizzes enable row level security;
alter table public.quiz_questions enable row level security;
alter table public.chat_messages enable row level security;
alter table public.subscriptions enable row level security;
create policy "profiles own rows" on public.profiles for all using (auth.uid() = id) with check (auth.uid() = id);
create policy "notes own rows" on public.notes for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "transcripts through note" on public.transcripts for all using (exists (select 1 from public.notes n where n.id = note_id and n.user_id = auth.uid())) with check (exists (select 1 from public.notes n where n.id = note_id and n.user_id = auth.uid()));
create policy "chunks through note" on public.note_chunks for all using (exists (select 1 from public.notes n where n.id = note_id and n.user_id = auth.uid())) with check (exists (select 1 from public.notes n where n.id = note_id and n.user_id = auth.uid()));
create policy "flashcards own rows" on public.flashcards for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "quizzes own rows" on public.quizzes for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "quiz questions through quiz" on public.quiz_questions for all using (exists (select 1 from public.quizzes q where q.id = quiz_id and q.user_id = auth.uid())) with check (exists (select 1 from public.quizzes q where q.id = quiz_id and q.user_id = auth.uid()));
create policy "chat own rows" on public.chat_messages for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "subscription own row" on public.subscriptions for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create or replace function public.handle_new_user() returns trigger language plpgsql security definer as $$ begin insert into public.profiles (id, display_name) values (new.id, coalesce(new.raw_user_meta_data->>'full_name', new.email)); insert into public.subscriptions (user_id) values (new.id); return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
